apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Anand-1110/atlas.git
    targetRevision: main
    path: k8s/helm-charts
    helm:
      valueFiles: []

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
